openapi: 3.0.0
info:
  title: Library System API
  version: 1.0.0
paths:
  /members:
    get:
      summary: Shows all existing members and their borrowing quantity
      tags:
        - Members
      responses:
        '200':
          description: List of members retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberListResponse'

    post:
      summary: Create a new member
      tags:
        - Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMember'
      responses:
        '201':
          description: Member successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /members/{code}:
    get:
      summary: Get a specific member by code
      tags:
        - Members
      parameters:
        - in: path
          name: code
          required: true
          description: Code of the member to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Member successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '404':
          description: Member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update a member
      tags:
        - Members
      parameters:
        - in: path
          name: code
          required: true
          description: Code of the member to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMember'
      responses:
        '200':
          description: Member successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a member
      tags:
        - Members
      parameters:
        - in: path
          name: code
          required: true
          description: Code of the member to delete
          schema:
            type: string
      responses:
        '200':
          description: Member successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '404':
          description: Member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
components:
  schemas:
    MemberListResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              name:
                type: string
              borrowingQuantity:
                type: integer
                format: int32
    MemberResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/Member'
    Member:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        penaltyEndDate:
          type: string
          format: date
    NewMember:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
    UpdateMember:
      type: object
      properties:
        name:
          type: string
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
