openapi: 3.0.0
info:
  title: Library System API
  version: 1.0.0
paths:
  /borrowings/borrow:
    post:
      summary: Borrow a book
      tags:
        - Borrowings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memberCode:
                  type: string
                bookCode:
                  type: string
      responses:
        '201':
          description: Book borrowed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Borrowing'
        '400':
          description: Bad request

  /borrowings/return:
    post:
      summary: Return a borrowed book
      tags:
        - Borrowings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memberCode:
                  type: string
                bookCode:
                  type: string
      responses:
        '200':
          description: Book returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Borrowing'
        '400':
          description: Bad request

components:
  schemas:
    Borrowing:
      type: object
      properties:
        memberCode:
          type: string
        bookCode:
          type: string
        borrowDate:
          type: string
          format: date-time
        returnDate:
          type: string
          format: date-time
